## Tensorflow 函数详解

### 1. tf.random_uniform

    tf.random_uniform((4, 4), minval=low, maxval=high, dtype=tf.float32) 返回4*4的矩阵，产生于low和high之间，产生的值是均匀分布的。

In [1]:
import tensorflow as tf
import numpy as np
 
with tf.Session() as sess:
    print(sess.run(tf.random_uniform(
        (4, 4), minval=-0.5,
        maxval=0.5,dtype=tf.float32)))

[[-0.46532667 -0.45245385 -0.09505916  0.0079987 ]
 [-0.22305739  0.27954495 -0.4618752  -0.24561155]
 [-0.19420075 -0.30681014  0.21666753  0.22821605]
 [ 0.0696162   0.48100567  0.12775195  0.23838639]]


### 2. tf.nn.embedding_lookup

函数的用法主要是选取一个张量里面索引对应的元素。

    tf.nn.embedding_lookup（tensor, id）:tensor就是输入张量，id就是张量对应的索引

In [6]:
import tensorflow as tf;
import numpy as np;
 
c = np.random.random([10,1])
b = tf.nn.embedding_lookup(c, [1, 3])
 
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(b))
    print(c)

[[ 0.35167829]
 [ 0.36811982]]
[[ 0.19015111]
 [ 0.35167829]
 [ 0.80507801]
 [ 0.36811982]
 [ 0.62456547]
 [ 0.20043036]
 [ 0.66160563]
 [ 0.58482013]
 [ 0.07036611]
 [ 0.62459213]]


### 3. tf.layers.dense

    dense(
        inputs,
        units,
        activation=None,
        use_bias=True,
        kernel_initializer=None,
        bias_initializer=tf.zeros_initializer(),
        kernel_regularizer=None,
        bias_regularizer=None,
        activity_regularizer=None,
        trainable=True,
        name=None,
        reuse=None
    )
 
- inputs: 输入数据，2维tensor.
- units: 该层的神经单元结点数。
- activation: 激活函数.
- use_bias: Boolean型，是否使用偏置项.
- kernel_initializer: 卷积核的初始化器.
- bias_initializer: 偏置项的初始化器，默认初始化为0.
- kernel_regularizer: 卷积核化的正则化，可选.
- bias_regularizer: 偏置项的正则化，可选.
- activity_regularizer: 输出的正则化函数.
- trainable: Boolean型，表明该层的参数是否参与训练。如果为真则变量加入到图集合中 GraphKeys.TRAINABLE_VARIABLES (see tf.Variable).
- name: 层的名字.
- reuse: Boolean型, 是否重复使用参数.

全连接层执行操作 outputs = activation(inputs.kernel + bias)

如果执行结果不想进行激活操作，则设置activation=None。

### 4. tf.concat

    tf.concat（[list1, list2], axis）
    
* 用于合并两个迭代器（比如列表）。axis表示合并的方向。0表示竖直合并，1表示水平

In [11]:
import tensorflow as tf;
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np;
import os
 
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
 
print(tf.Session().run(tf.concat([t1, t2], 0)))
print(tf.Session().run(tf.concat([t1, t2], 1)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 5. tf.layers.dense 和 tf.contrib.layers.fully_connected的区别

TensorFlow的tf.layers和ctf.contrib.layers都提供了相关用于搭建神经网络的模块，但同一版本额和不同版本之间均存在区别

讨论一下tf.layers.dense和tf.contrib.layers.fully_connected的区别，二者都可以用于构建全连接层。参考tensorflow的文档，二者的参数如下，

* tf.layers.dense

    tf.layers.dense(
        inputs,
        units,
        activation=None,
        use_bias=True,
        kernel_initializer=None,
        bias_initializer=tf.zeros_initializer(),
        kernel_regularizer=None,
        bias_regularizer=None,
        activity_regularizer=None,
        kernel_constraint=None,
        bias_constraint=None,
        trainable=True,
        name=None,
        reuse=None
    )
    
* tf.contrib.layers.fully-connected

    fully_connected(
        inputs,
        num_outputs,
        activation_fn=tf.nn.relu,
        normalizer_fn=None,
        normalizer_params=None,
        weights_initializer=initializers.xavier_initializer(),
        weights_regularizer=None,
        biases_initializer=tf.zeros_initializer(),
        biases_regularizer=None,
        reuse=None,
        variables_collections=None,
        outputs_collections=None,
        trainable=True,
        scope=None
    )
    
可以看出，tf.layers.dense相对更简单，没有提供默认的activation和kernel_initializer, 而后者这两个参数都做了默认的初始化。使用时一定要显示说明这些，否则会出现不可控的错误。。。

### 6. tf.reduce_sum

    tf.reduce_sum(input_tensor, axis=None, keep_dims=False, name=None, reduction_indices=None)

函数意义：将矩阵的元素相加，可以按列，也可以按行，或者先按列后按行

这样的函数在tensorflow中还有很多: 

tf.reduce_prod #沿维度相乘

tf.reduce_min #沿维度找最小

tf.reduce_max #沿维度找最大

tf.reduce_mean #沿维度求平均

tf.reduce_all#沿维度与操作

tf.reduce_any#沿维度或操作

具体可以参考[点击打开链接](https://www.jianshu.com/p/7fbce28e85a4)

### 7. 用tf.expand_dims()来增加维度

TensorFlow中，想要维度增加一维，可以使用tf.expand_dims(input, dim, name=None)函数。当然，我们常用tf.reshape(input, shape=[])也可以达到相同效果，但是有些时候在构建图的过程中，placeholder没有被feed具体的值，这时就会包下面的错误：TypeError: Expected binary or unicode string, got 1 

在这种情况下，我们就可以考虑使用expand_dims来将维度加1。比如我自己代码中遇到的情况，在对图像维度降到二维做特定操作后，要还原成四维[batch, height, width, channels]，前后各增加一维。如果用reshape，则因为上述原因报错

In [ ]:
one_img2 = tf.reshape(one_img, shape=[1, one_img.get_shape()[0].value, one_img.get_shape()[1].value, 1])

用下面的方法可以实现：

In [ ]:
one_img = tf.expand_dims(one_img, 0)
one_img = tf.expand_dims(one_img, -1) #-1表示最后一维

在最后，给出官方的例子和说明

    # 't' is a tensor of shape [2]
    shape(expand_dims(t, 0)) ==> [1, 2]
    shape(expand_dims(t, 1)) ==> [2, 1]
    shape(expand_dims(t, -1)) ==> [2, 1]

    # 't2' is a tensor of shape [2, 3, 5]
    shape(expand_dims(t2, 0)) ==> [1, 2, 3, 5]
    shape(expand_dims(t2, 2)) ==> [2, 3, 1, 5]
    shape(expand_dims(t2, 3)) ==> [2, 3, 5, 1]

### 8. tf.nn.conv2d()使用

* [tf.nn.conv2d()使用](https://blog.csdn.net/LoseInVain/article/details/78935192)

### 9. tf.reset_default_graph

tf.reset_default_graph函数用于清除默认图形堆栈并重置全局默认图形。 
注意：默认图形是当前线程的一个属性。该tf.reset_default_graph函数只适用于当前线程。当一个tf.Session或者tf.InteractiveSession激活时调用这个函数会导致未定义的行为。调用此函数后使用任何以前创建的tf.Operation或tf.Tensor对象将导致未定义的行为。

可能引发的异常：

- AssertionError：如果在嵌套图中调用此函数则会引发此异常。

### 10. tf.Graph



## Reference

* [TensorFlow 1.0后与以前代码不兼容解决-CIFAR-10报错解决](https://blog.csdn.net/shine19930820/article/details/76436765)